export const GET_ALL_UNDER_MANAGER_REQUEST = "GET_ALL_UNDER_MANAGER_REQUEST";
export const GET_ALL_UNDER_MANAGER_SUCCESS = "GET_ALL_UNDER_MANAGER_SUCCESS";
export const GET_ALL_UNDER_MANAGER_FAIL = "GET_ALL_UNDER_MANAGER_FAIL";

export const SEND_ALL_RATINGS_REQUEST = "SEND_ALL_RATINGS_REQUEST";
export const SEND_ALL_RATINGS_SUCCESS = "SEND_ALL_RATINGS_SUCCESS";
export const SEND_ALL_RATINGS_FAIL = "SEND_ALL_RATINGS_FAIL";

export const GET_ALL_DATA_REQUEST = "GET_ALL_DATA_REQUEST";
export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_FAIL = "GET_ALL_DATA_FAIL";

