export const FORGOT_PASS_EMAIL_REQUEST = "FORGOT_PASS_EMAIL_REQUEST";
export const FORGOT_PASS_EMAIL_SUCCESS = "FORGOT_PASS_EMAIL_SUCCESS";
export const FORGOT_PASS_EMAIL_FAIL = "FORGOT_PASS_EMAIL_FAIL";


export const REST_PASSWORD_REQUEST = "REST_PASSWORD_REQUEST";
export const REST_PASSWORD_SUCCESS = "REST_PASSWORD_SUCCESS";
export const REST_PASSWORD_FAIL = "REST_PASSWORD_FAIL";

