export const SAVE_TIME_SHEET_ENTRY_REQUEST = "SAVE_TIME_SHEET_REQUEST";
export const SAVE_TIME_SHEET_ENTRY_SUCCESS = "SAVE_TIME_SHEET_SUCCESS";
export const SAVE_TIME_SHEET_ENTRY_FAIL = "SAVE_TIME_SHEET_FAIL";

export const CLEAR_SUCCESS_FLAG = "CLEAR_SUCCESS_FLAG";

export const UPDATE_TIME_SHEET_ENTRY_REQUEST =
  "UPDATE_TIME_SHEET_ENTRY_REQUEST";
export const UPDATE_TIME_SHEET_ENTRY_SUCCESS =
  "UPDATE_TIME_SHEET_ENTRY_SUCCESS";
export const UPDATE_TIME_SHEET_ENTRY_FAIL = "UPDATE_TIME_SHEET_ENTRY_FAIL";

export const GET_TIME_SHEET_ENTRY_REQUEST = "GET_TIME_SHEET_ENTRY_REQUEST";
export const GET_TIME_SHEET_ENTRY_SUCCESS = "GET_TIME_SHEET_ENTRY_SUCCESS";
export const GET_TIME_SHEET_ENTRY_FAIL = "GET_TIME_SHEET_ENTRY_FAIL";

export const SUBMIT_TIME_SHEET_APPROVAL_REQUEST =
  "SUBMIT_TIME_SHEET_APPROVAL_REQUEST";
export const SUBMIT_TIME_SHEET_APPROVAL_SUCCESS =
  "SUBMIT_TIME_SHEET_APPROVAL_SUCCESS";
export const SUBMIT_TIME_SHEET_APPROVAL_FAIL =
  "SUBMIT_TIME_SHEET_APPROVAL_FAIL";

export const GET_TIME_SHEET_APPROVAL_REQUEST =
  "GET_TIME_SHEET_APPROVAL_REQUEST";
export const GET_TIME_SHEET_APPROVAL_SUCCESS =
  "GET_TIME_SHEET_APPROVAL_SUCCESS";
export const GET_TIME_SHEET_APPROVAL_FAIL = "GET_TIME_SHEET_APPROVAL_FAIL";

export const APPROVE_TIME_SHEET_REQUEST = "APPROVE_TIME_SHEET_REQUEST";
export const APPROVE_TIME_SHEET_SUCCESS = "APPROVE_TIME_SHEET_SUCCESS";
export const APPROVE_TIME_SHEET_FAIL = "APPROVE_TIME_SHEET_FAIL";

export const REJECT_TIME_SHEET_REQUEST = "REJECT_TIME_SHEET_REQUEST";
export const REJECT_TIME_SHEET_SUCCESS = "REJECT_TIME_SHEET_SUCCESS";
export const REJECT_TIME_SHEET_FAIL = "REJECT_TIME_SHEET_FAIL";
export const RESET_UPDATE_TIME_SHEET_ENTRY_FAIL =
  "RESET_UPDATE_TIME_SHEET_ENTRY_FAIL";


  export const GET_LAST_THREE_DATES_TIMESHEET_ENTRY_REQUEST = " GET_LAST_THREE_DATES_TIMESHEET_ENTRY_REQUEST";
export const GET_LAST_THREE_DATES_TIMESHEET_ENTRY_SUCCESS = " GET_LAST_THREE_DATES_TIMESHEET_ENTRY_SUCCESS";
export const  GET_LAST_THREE_DATES_TIMESHEET_ENTRY_FAIL = " GET_LAST_THREE_DATES_TIMESHEET_ENTRY_FAIL";


export const GET_MOST_COMMON_TIMES_REQUEST = " GET_MOST_COMMON_TIMES_REQUEST";
export const GET_MOST_COMMON_TIMES_SUCCESS = " GET_MOST_COMMON_TIMES_SUCCESS";
export const  GET_MOST_COMMON_TIMES_FAIL = " GET_MOST_COMMON_TIMES_ENTRY_FAIL";