export const SEARCH_USERNAME_REQUEST = "SEARCH_USERNAME_REQUEST";
export const SEARCH_USERNAME_SUCCESS = "SEARCH_USERNAME_SUCCESS";
export const  SEARCH_USERNAME_FAILURE = "SEARCH_USERNAME_FAILURE";

export const GET_ALL_TIMESTEET_APPROVERS_REQUEST = "GET_ALL_TIMESTEET_APPROVERS_REQUEST";
export const GET_ALL_TIMESTEET_APPROVERS_SUCCESS = "GET_ALL_TIMESTEET_APPROVERS_SUCCESS";
export const GET_ALL_TIMESTEET_APPROVERS_FAILURE = "GET_ALL_TIMESTEET_APPROVERS_FAILURE";


export const GET_ALL_TIMESHEET_FOR_ADMIN_REQUEST = "GET_ALL_TIMESHEET_FOR_ADMIN_REQUEST";
export const GET_ALL_TIMESHEET_FOR_ADMIN_SUCCESS = "GET_ALL_TIMESHEET_FOR_ADMIN_SUCCESS";
export const GET_ALL_TIMESHEET_FOR_ADMIN_FAILURE = "GET_ALL_TIMESHEET_FOR_ADMIN_FAILURE";

