export const FETCH_ALL_USERS_REQUEST = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

export const SEARCH_EMPLOYEE_REQUEST = "SEARCH_EMPLOYEE_REQUEST";
export const SEARCH_EMPLOYEE_SUCCESS = "SEARCH_EMPLOYEE_SUCCESS";
export const SEARCH_EMPLOYEE_FAIL = "SEARCH_EMPLOYEE_FAIL";

//country state city

export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

export const FETCH_STATES_REQUEST = 'FETCH_STATES_REQUEST';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const FETCH_STATES_FAILURE = 'FETCH_STATES_FAILURE';

export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

export const FETCH_LOCATION_DATA_SUCCESS = 'FETCH_LOCATION_DATA_SUCCESS';
export const SET_SELECTED_COUNTRY_ID = 'SET_SELECTED_COUNTRY_ID';

// export  const EDIT_USER_DETAILS_SUCCESS = 'EDIT_USER_DETAILS_SUCCESS';
// export  const EDIT_USER_DETAILS_REQUEST = 'EDIT_USER_DETAILS_REQUEST';
// export  const EDIT_USER_DETAILS_FAIL = 'EDIT_USER_DETAILS_FAIL';
export const GET_ALL_CITYS = 'GET_ALL_CITYS';

export const SEARCH_EMPLOYEEANDPROJECT_REQUEST ="SEARCH_EMPLOYEEANDPROJECT_REQUEST";
export const SEARCH_EMPLOYEEANDPROJECT_SUCCESS ="SEARCH_EMPLOYEEANDPROJECT_SUCCESS";
export const SEARCH_EMPLOYEEANDPROJECT_FAILURE ="SEARCH_EMPLOYEEANDPROJECT_FAILURE";


