export const FETCH_ALL_USERS_REQUEST = 'FETCH_ALL_USERS_REQUEST';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";

export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';

export const GET_ALL_CITYS = 'GET_ALL_CITYS';

export const SEARCH_EMPLOYEEANDPROJECT_REQUEST ="SEARCH_EMPLOYEEANDPROJECT_REQUEST";
export const SEARCH_EMPLOYEEANDPROJECT_SUCCESS ="SEARCH_EMPLOYEEANDPROJECT_SUCCESS";
export const SEARCH_EMPLOYEEANDPROJECT_FAILURE ="SEARCH_EMPLOYEEANDPROJECT_FAILURE";

