export const GET_ALL_LEAVES_FOR_ADMIN_REQUEST =
  "GET_ALL_LEAVES_FOR_ADMIN_REQUEST";
export const GET_ALL_LEAVES_FOR_ADMIN_SUCCESS =
  "GET_ALL_LEAVES_FOR_ADMIN_SUCCESS";
export const GET_ALL_LEAVES_FOR_ADMIN_FAILURE =
  "GET_ALL_LEAVES_FOR_ADMIN_FAILURE";

export const GET_ALL_LEAVES_APPROVERS_REQUEST =
  " GET_ALL_LEAVES_APPROVERS_REQUEST";
export const GET_ALL_LEAVES_APPROVERS_SUCCESS =
  "GET_ALL_LEAVES_APPROVERS_SUCCESS";
export const GET_ALL_LEAVES_APPROVERS_FAILURE =
  "GET_ALL_LEAVES_APPROVERS_FAILURE";
