export const DASHBOARD_PROJECT_DETAILS_REQUEST =
  "DASHBOARD_PROJECT_DETAILS_REQUEST";
export const DASHBOARD_PROJECT_DETAILS_SUCCESS =
  "DASHBOARD_PROJECT_DETAILS_SUCCESS";
export const DASHBOARD_PROJECT_DETAILS_FAIL = "DASHBOARD_PROJECT_DETAILS_FAIL";

export const DASHBOARD_PROJECT_RESOURCES_REQUEST =
  "DASHBOARD_PROJECT_RESOURCES_REQUEST";
export const DASHBOARD_PROJECT_RESOURCES_SUCCESS =
  "DASHBOARD_PROJECT_RESOURCES_SUCCESS";
export const DASHBOARD_PROJECT_RESOURCES_FAIL =
  "DASHBOARD_PROJECT_RESOURCES_FAIL";
