export const GET_ALL_PROJECTLIST_REQUEST = "GET_ALL_PROJECTLIST_REQUEST";
export const GET_ALL_PROJECTLIST_SUCCESS = "GET_ALL_PROJECTLIST_SUCCESS";
export const GET_ALL_PROJECTLIST_FAIL = "GET_ALL_PROJECTLIST_FAIL";

export const GET_WORKSPACE_DATA_REQUEST = "GET_WORKSPACE_DATA_REQUEST";
export const GET_WORKSPACE_DATA_SUCCESS = "GET_WORKSPACE_DATA_SUCCESS";
export const GET_WORKSPACE_DATA_FAIL = "GET_WORKSPACE_DATA_FAIL";


export const GET_PROJECT_PERFORMANCE_REQUEST = "GET_PROJECT_PERFORMANCE_REQUEST";
export const GET_PROJECT_PERFORMANCE_SUCCESS = "GET_PROJECT_PERFORMANCE_SUCCESS";
export const GET_PROJECT_PERFORMANCE_FAIL = "GET_PROJECT_PERFORMANCE_FAIL";

export const RATING_DATA_REQUEST = "RATING_DATA_REQUEST";
export const RATING_DATA_SUCCESS = "RATING_DATA_SUCCESS";
export const RATING_DATA_FAIL = "RATING_DATA_FAIL";

export const MYSPACE_ACTIVITY_REQUEST = "MYSPACE_ACTIVITY_REQUEST";
export const MYSPACE_ACTIVITY_SUCCESS = "MYSPACE_ACTIVITY_SUCCESS";
export const MYSPACE_ACTIVITY_FAIL = "MYSPACE_ACTIVITY_FAIL";

export const TODAY_ACTIVITY_REQUEST = "TODAY_ACTIVITY_REQUEST";
export const TODAY_ACTIVITY_SUCCESS = "TODAY_ACTIVITY_SUCCESS";
export const TODAY_ACTIVITY_FAIL = "TODAY_ACTIVITY_FAIL";
export const GET_ALL_REPORTES_REQUEST = "GET_ALL_REPORTES_REQUEST";
export const GET_ALL_REPORTES_SUCCESS = "GET_ALL_REPORTES_SUCCESS";
export const GET_ALL_REPORTES_FAIL = "GET_ALL_REPORTES_FAIL";

export const GET_ALL_TEAMEMBERS_REQUEST = "GET_ALL_TEAMEMBERS_REQUEST";
export const GET_ALL_TEAMEMBERS_SUCCESS = "GET_ALL_TEAMEMBERS_SUCCESS";
export const GET_ALL_TEAMEMBERS_FAIL = "GET_ALL_TEAMEMBERS_FAIL";

export const GET_PROJECT_PROGRESS_GRAPH_DATA_REQUEST = "GET_PROJECT_PROGRESS_GRAPH_DATA_REQUEST";
export const GET_PROJECT_PROGRESS_GRAPH_DATA_SUCCESS = "GET_PROJECT_PROGRESS_GRAPH_DATA_SUCCESS";
export const GET_PROJECT_PROGRESS_GRAPH_DATA_FAIL = "GET_PROJECT_PROGRESS_GRAPH_DATA_FAIL";
