export const GET_ALL_PROJECTLIST_REQUEST = "GET_ALL_PROJECTLIST_REQUEST";
export const GET_ALL_PROJECTLIST_SUCCESS = "GET_ALL_PROJECTLIST_SUCCESS";
export const GET_ALL_PROJECTLIST_FAIL = "GET_ALL_PROJECTLIST_FAIL";
