export const GET_TIMESHEET_REPORTS_REQUEST = "GET_TIMESHEET_REPORTS_REQUEST";
export const GET_TIMESHEET_REPORTS_SUCCESS = "GET_TIMESHEET_REPORTS_SUCCESS";
export const GET_TIMESHEET_REPORTS_FAIL = "GET_TIMESHEET_REPORTS_FAIL";

export const GET_SINGLE_DOWNLOAD_REPORT_REQUEST = "GET_SINGLE_DOWNLOAD_REPORT_REQUEST";
export const GET_SINGLE_DOWNLOAD_REPORT_SUCCESS = "GET_SINGLE_DOWNLOAD_REPORT_SUCCESS";
export const GET_SINGLE_DOWNLOAD_REPORT_FAIL = "GET_SINGLE_DOWNLOAD_REPORT_FAIL";

export const GET_DOWNLOAD_REPORTS_REQUEST = "GET_SINGLE_DOWNLOAD_REPORTS_REQUEST";
export const GET_DOWNLOAD_REPORTS_SUCCESS = "GET_SINGLE_DOWNLOAD_REPORTS_SUCCESS";
export const GET_DOWNLOAD_REPORTS_FAIL = "GET_SINGLE_DOWNLOAD_REPORTS_FAIL";
