export const FETCH_ALL_PROJECTS_REQUEST = "FETCH_ALL_PROJECTS_REQUEST";
export const FETCH_ALL_PROJECTS_SUCCESS = "FETCH_ALL_PROJECTS_SUCCESS";
export const FETCH_ALL_PROJECTS_FAILURE = "FETCH_ALL_PROJECTS_FAILURE";

export const FETCH_EMPLOYEE_SEARCH_REQUEST = "FETCH_EMPLOYEE_SEARCH_REQUEST";
export const FETCH_EMPLOYEE_SEARCH_SUCCESS = "FETCH_EMPLOYEE_SEARCH_SUCCESS";
export const FETCH_EMPLOYEE_SEARCH_FAILURE = "FETCH_EMPLOYEE_SEARCH_FAILURE";

export const FETCH_ALL_DOMAIN_REQUEST = "FETCH_ALL_DOMAIN_REQUEST";
export const FETCH_ALL_DOMAIN_SUCCESS = "FETCH_ALL_DOMAIN_SUCCESS";
export const FETCH_ALL_DOMAIN_FAILURE = "FETCH_ALL_DOMAIN_FAILURE";

export const FETCH_ALLOCATION_SEARCH_REQUEST =
  "FETCH_ALLOCATION_SEARCH_REQUEST";
export const FETCH_ALLOCATION_SEARCH_SUCCESS =
  "FETCH_ALLOCATION_SEARCH_SUCCESS";
export const FETCH_ALLOCATION_SEARCH_FAILURE =
  "FETCH_ALLOCATION_SEARCH_FAILURE";
