export const FETCH_ALL_PROJECTS_REQUEST = "FETCH_ALL_PROJECTS_REQUEST";
export const FETCH_ALL_PROJECTS_SUCCESS = "FETCH_ALL_PROJECTS_SUCCESS";
export const FETCH_ALL_PROJECTS_FAILURE = "FETCH_ALL_PROJECTS_FAILURE";

export const FETCH_EMPLOYEE_SEARCH_REQUEST = "FETCH_EMPLOYEE_SEARCH_REQUEST";
export const FETCH_EMPLOYEE_SEARCH_SUCCESS = "FETCH_EMPLOYEE_SEARCH_SUCCESS";
export const FETCH_EMPLOYEE_SEARCH_FAILURE = "FETCH_EMPLOYEE_SEARCH_FAILURE";

export const FETCH_ALL_DOMAIN_REQUEST = "FETCH_ALL_DOMAIN_REQUEST";
export const FETCH_ALL_DOMAIN_SUCCESS = "FETCH_ALL_DOMAIN_SUCCESS";
export const FETCH_ALL_DOMAIN_FAILURE = "FETCH_ALL_DOMAIN_FAILURE";

export const FETCH_ALLOCATION_SEARCH_REQUEST =
  "FETCH_ALLOCATION_SEARCH_REQUEST";
export const FETCH_ALLOCATION_SEARCH_SUCCESS =
  "FETCH_ALLOCATION_SEARCH_SUCCESS";
export const FETCH_ALLOCATION_SEARCH_FAILURE =
  "FETCH_ALLOCATION_SEARCH_FAILURE";

export const FETCH_CLIENT_NAME_REQUEST = "FETCH_CLIENT_NAME_REQUEST";
export const FETCH_CLIENT_NAME_SUCCESS = "FETCH_CLIENT_NAME_SUCCESS";
export const FETCH_CLIENT_NAME_FAILURE = "FETCH_CLIENT_NAME_FAILURE";

export const FETCH_RESOURCES_NAME_DESIGNATION_SEARCH_REQUEST =
  "FETCH_RESOURCES_NAME_DESIGNATION_SEARCH_REQUEST";
export const FETCH_RESOURCES_NAME_DESIGNATION_SEARCH_SUCCESS =
  "FETCH_RESOURCES_NAME_DESIGNATION_SEARCH_SUCCESS";
export const FETCH_RESOURCES_NAME_DESIGNATION_SEARCH_FAILURE =
  "FETCH_RESOURCES_NAME_DESIGNATION_SEARCH_FAILURE";

export const FETCH_CLIENT_DETAILS_REQUEST = "FETCH_CLIENT_DETAILS_REQUEST";
export const FETCH_CLIENT_DETAILS_SUCCESS = "FETCH_CLIENT_DETAILS_SUCCESS";
export const FETCH_CLIENT_DETAILS_FAILURE = "FETCH_CLIENT_DETAILS_FAILURE";

export const GET_ALL_COUNTRY_CITY_STATE_REQUEST =
  " GET_ALL_COUNTRY_CITY_STATE_REQUEST";
export const GET_ALL_COUNTRY_CITY_STATE_SUCCESS =
  " GET_ALL_COUNTRY_CITY_STATE_SUCCESS";
export const GET_ALL_COUNTRY_CITY_STATE_FAILURE =
  " GET_ALL_COUNTRY_CITY_STATE_FAILURE";

export const SAVE_CREATE_PROJECT_REQUEST = "SAVE_CREATE_PROJECT_REQUEST";
export const SAVE_CREATE_PROJECT_SUCCESS = "SAVE_CREATE_PROJECT_SUCCESS";
export const SAVE_CREATE_PROJECT_FAIL = "SAVE_CREATE_PROJECT_FAIL";

export const FETCH_SEARCH_CLIENT_NAME_PROJECT_NAME_REQUEST =
  "FETCH_SEARCH_CLIENT_NAME_PROJECT_NAME_REQUEST";
export const FETCH_SEARCH_CLIENT_NAME_PROJECT_NAME_SUCCESS =
  "FETCH_SEARCH_CLIENT_NAME_PROJECT_NAME_SUCCESS";
export const FETCH_SEARCH_CLIENT_NAME_PROJECT_NAME_FAIL =
  "FETCH_SEARCH_CLIENT_NAME_PROJECT_NAME_FAIL";

export const SAVE_CREATE_COST_INCURRED_REQUEST =
  "SAVE_CREATE_COST_INCURRED_REQUEST";
export const SAVE_CREATE_COST_INCURRED_SUCCESS =
  "SAVE_CREATE_COST_INCURRED_SUCCESS";
export const SAVE_CREATE_COST_INCURRED_FAIL = "SAVE_CREATE_COST_INCURRED_FAIL";

export const FETCH_PROJECT_DETAILS_REQUEST = "FETCH_PROJECT_DETAILS_REQUEST";
export const FETCH_PROJECT_DETAILS_SUCCESS = "FETCH_PROJECT_DETAILS_SUCCESS";
export const FETCH_PROJECT_DETAILS_FAILURE = "FETCH_PROJECT_DETAILS_FAILURE";

export const FETCH_ALL_COST_INCURRED_REQUEST =
  "FETCH_ALL_COST_INCURRED_REQUEST";
export const FETCH_ALL_COST_INCURRED_SUCCESS =
  "FETCH_ALL_COST_INCURRED_SUCCESS";
export const FETCH_ALL_COST_INCURRED_FAILURE =
  "FETCH_ALL_COST_INCURRED_FAILURE";

export const FETCH_RESOURCE_DETAILS_POPUP_REQUEST =
  "FETCH_RESOURCE_DETAILS_POPUP_REQUEST";
export const FETCH_RESOURCE_DETAILS_POPUP_SUCCESS =
  "FETCH_RESOURCE_DETAILS_POPUP_SUCCESS";
export const FETCH_RESOURCE_DETAILS_POPUP_FAILURE =
  "FETCH_RESOURCE_DETAILS_POPUP_FAILURE";

export const FETCH_ALL_RESOURCE_REQUEST = "FETCH_ALL_RESOURCE__REQUEST";
export const FETCH_ALL_RESOURCE__SUCCESS = "FETCH_ALL_RESOURCE__SUCCESS";
export const FETCH_ALL_RESOURCE__FAILURE = "FETCH_ALL_RESOURCE__FAILURE";

export const SAVE_CREATE_RESOURCES_REQUEST = "SAVE_CREATE_RESOURCES_REQUEST";
export const SAVE_CREATE_RESOURCES_SUCCESS = "SAVE_CREATE_RESOURCES_SUCCESS";
export const SAVE_CREATE_RESOURCES_FAIL = "SAVE_CREATE_RESOURCES_FAIL";
