export const APPROVAL_LEAVE_DATES_REQUEST = "APPROVAL_LEAVE_DATES_REQUEST";
export const APPROVAL_LEAVE_DATES_SUCCESS = "APPROVAL_LEAVE_DATES_SUCCESS";
export const APPROVAL_LEAVE_DATES_FAIL = "APPROVAL_LEAVE_DATES_FAIL";

export const APPROVAL_LEAVE_TEAM_MEMBER_REQUEST =
  "APPROVAL_LEAVE_TEAM_MEMBER_REQUEST";
export const APPROVAL_LEAVE_TEAM_MEMBER_SUCCESS =
  "APPROVAL_LEAVE_TEAM_MEMBER_SUCCESS";
export const APPROVAL_LEAVE_TEAM_MEMBER_FAIL =
  "APPROVAL_LEAVE_TEAM_MEMBER_FAIL";

export const APPROVE_LEAVES_REQUEST = "APPROVE_LEAVES_REQUEST";
export const APPROVE_LEAVES_SUCCESS = "APPROVE_LEAVES_SUCCESS";
export const APPROVE_LEAVES_FAIL = "APPROVE_LEAVES_FAIL";

export const REJECT_LEAVES_REQUEST = "REJECT_LEAVES_REQUEST";
export const REJECT_LEAVES_SUCCESS = "REJECT_LEAVES_SUCCESS";
export const REJECT_LEAVES_FAIL = "REJECT_LEAVES_FAIL";

export const GET_LEAVE_REQUEST = "GET_LEAVE_REQUEST";
export const GET_LEAVE_SUCCESS = "GET_LEAVE_SUCCESS";
export const GET_LEAVE_FAIL = "GET_LEAVE_FAIL";


export const DOWNLOAD_FILE_REQUEST = 'DOWNLOAD_FILE_REQUEST';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const DOWNLOAD_FILE_FAIL = 'DOWNLOAD_FILE_FAIL';