// actionTypes.js
export const FETCH_LEAVE_HISTORY_REQUEST = 'FETCH_LEAVE_HISTORY_REQUEST';
export const FETCH_LEAVE_HISTORY_SUCCESS = 'FETCH_LEAVE_HISTORY_SUCCESS';
export const FETCH_LEAVE_HISTORY_FAILURE = 'FETCH_LEAVE_HISTORY_FAILURE';
