export const LEAVE_BALANCE_REQUEST = "LEAVES_REQUEST";
export const LEAVE_BALANCE_SUCCESS = "LEAVES_SUCCESS";
export const LEAVE_BALANCE_FAIL = "LEAVES_FAIL";

export const HOLIDAY_LIST_REQUEST = "HOLIDAY_LIST_REQUEST";
export const HOLIDAY_LIST_SUCCESS = "HOLIDAY_LIST_SUCCESS";
export const HOLIDAY_LIST_FAIL = "HOLIDAY_LIST_FAIL";

export const SEARCH_EMAIL_REQUEST = "SEARCH_EMAIL_REQUEST";
export const SEARCH_EMAIL_SUCCESS = "SEARCH_EMAIL_SUCCESS";
export const SEARCH_EMAIL_FAIL = "SEARCH_EMAIL_FAIL";

export const SAVE_LEAVE_FORM_REQUEST = "SAVE_LEAVE_FORM_REQUEST";
export const SAVE_LEAVE_FORM_SUCCESS = "SAVE_LEAVE_FORM_SUCCESS";
export const SAVE_LEAVE_FORM_FAIL = "SAVE_LEAVE_FORM_FAIL";

export const SAVE_SUBMIT_LEAVE_FORM_REQUEST = "SAVE_SUBMIT_LEAVE_FORM_REQUEST";
export const SAVE_SUBMIT_LEAVE_FORM_SUCCESS = "SAVE_SUBMIT_LEAVE_FORM_SUCCESS";
export const SAVE_SUBMIT_LEAVE_FORM_FAIL = "SAVE_SUBMIT_LEAVE_FORM_FAIL";



export const DELETE_LEAVE_REQUEST = "DELETE_LEAVE_REQUEST";
export const DELETE_LEAVE_SUCCESS = "DELETE_LEAVE_SUCCESS";
export const DELETE_LEAVE_FAILURE = "DELETE_LEAVE_FAILURE";

export const ALL_EMPLOYEES_LEAVE_REQUEST = "ALL_EMPLOYEES_LEAVE_REQUEST";
export const ALL_EMPLOYEES_LEAVE_SUCCESS = "ALL_EMPLOYEES_LEAVE_SUCCESS";
export const ALL_EMPLOYEES_LEAVE_FAIL = "ALL_EMPLOYEES_LEAVE_FAIL";



