export const fixedHolidays = [
  {
    id: 1,
    holidayType: "HOLIDAY",
    name: "Republic Day",
    date: "2023-01-26",
    audit: null,
    status: true,
  },
  {
    id: 2,
    holidayType: "HOLIDAY",
    name: "Ugadi",
    date: "2023-03-22",
    audit: null,
    status: true,
  },
  {
    id: 3,
    holidayType: "HOLIDAY",
    name: "May Day",
    date: "2023-05-01",
    audit: null,
    status: true,
  },
  {
    id: 4,
    holidayType: "HOLIDAY",
    name: "Independence Day",
    date: "2023-08-15",
    audit: null,
    status: true,
  },
  {
    id: 6,
    holidayType: "HOLIDAY",
    name: "Ganesh Chaturthi",
    date: "2023-09-19",
    audit: null,
    status: true,
  },
  {
    id: 7,
    holidayType: "HOLIDAY",
    name: "Gandhi Jayanti",
    date: "2023-10-02",
    audit: null,
    status: true,
  },
  {
    id: 8,
    holidayType: "HOLIDAY",
    name: "Vijayadashami",
    date: "2023-10-24",
    audit: null,
    status: true,
  },
  {
    id: 9,
    holidayType: "HOLIDAY",
    name: "Kannada Rajyothsava",
    date: "2023-11-01",
    audit: null,
    status: true,
  },
  {
    id: 10,
    holidayType: "HOLIDAY",
    name: "Balipadyami, Deepavali",
    date: "2023-11-14",
    audit: null,
    status: true,
  },
  {
    id: 11,
    holidayType: "HOLIDAY",
    name: "Christmas",
    date: "2023-12-25",
    audit: null,
    status: true,
  },
];
export const optionalHolidays = [
  {
    id: 12,
    holidayType: "OPTIONLHOLIDAY",
    name: "Holi",
    date: "2023-03-08",
    audit: null,
    status: true,
  },
  {
    id: 13,
    holidayType: "OPTIONLHOLIDAY",
    name: "Good Friday",
    date: "2023-04-07",
    audit: null,
    status: true,
  },
  {
    id: 14,
    holidayType: "OPTIONLHOLIDAY",
    name: "Bakrid",
    date: "2023-06-29",
    audit: null,
    status: true,
  },
  {
    id: 15,
    holidayType: "OPTIONLHOLIDAY",
    name: "Varamahalakshmi Vrata",
    date: "2023-08-25",
    audit: null,
    status: true,
  },
  {
    id: 16,
    holidayType: "OPTIONLHOLIDAY",
    name: "Onam",
    date: "2023-08-29",
    audit: null,
    status: true,
  },
  {
    id: 17,
    holidayType: "OPTIONLHOLIDAY",
    name: "Sri Krishna Janmashtam",
    date: "2023-09-06",
    audit: null,
    status: true,
  },
  {
    id: 18,
    holidayType: "OPTIONLHOLIDAY",
    name: "Ayudh Puja",
    date: "2023-10-23",
    audit: null,
    status: true,
  },
];
