export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const UPDATE_ACCESS_TOKEN = "UPDATE_ACCESS_TOKEN";
