export const MASTER_DATA_REQUEST = "MASTER_DATA_REQUEST";
export const MASTER_DATA_SUCCESS = "MASTER_DATA_SUCCESS";
export const MASTER_DATA_FAIL = "MASTER_DATA_FAIL";

export const GET_ALL_SKILL_SUCCESS = "GET_ALL_SKILL_SUCCESS";

export const GET_ALL_DESIGNATION_SUCCESS = "GET_ALL_DESIGNATION_SUCCESS";

export  const GET_ALL_BAND_SUCCESS = "GET_ALL_BAND_SUCCESS";

export const GET_ALL_OFFICELOCAION_SUCCESS = "GET_ALL_OFFICELOCAION_SUCCESS"

export const GET_OFFICE_LOCATION_SUCCESS = "GET_OFFICE_LOCATION_SUCCESS"