export const MASTER_DATA_REQUEST = "MASTER_DATA_REQUEST";
export const MASTER_DATA_SUCCESS = "MASTER_DATA_SUCCESS";
export const MASTER_DATA_FAIL = "MASTER_DATA_FAIL";

export const GET_ALL_SKILL_SUCCESS = "GET_ALL_SKILL_SUCCESS";
export const GET_ALL_SKILL_REQUEST = "GET_ALL_SKILL_REQUEST";
export const GET_ALL_SKILL_FAIL = "GET_ALL_SKILL_FAIL";

export const GET_ALL_DESIGNATION_SUCCESS = "GET_ALL_DESIGNATION_SUCCESS";
export const GET_ALL_DESIGNATION_REQUEST = "GET_ALL_DESIGNATION_REQUEST";
export const GET_ALL_DESIGNATION_FAIL = "GET_ALL_DESIGNATION_FAIL";

export const GET_ALL_BAND_SUCCESS = "GET_ALL_BAND_SUCCESS";
export const GET_ALL_BAND_REQUEST = "GET_ALL_BAND_REQUEST";
export const GET_ALL_BAND_FAIL = "GET_ALL_BAND_FAIL";

export const GET_ALL_OFFICELOCAION_SUCCESS = "GET_ALL_OFFICELOCAION_SUCCESS";
export const GET_ALL_OFFICELOCAION_REQUEST = "GET_ALL_OFFICELOCAION_SUCCESS";
export const GET_ALL_OFFICELOCAION_FAIL = "GET_ALL_OFFICELOCAION_SUCCESS";

export const GET_OFFICE_LOCATION_SUCCESS = "GET_OFFICE_LOCATION_SUCCESS";
export const GET_OFFICE_LOCATION_REQUEST = "GET_OFFICE_LOCATION_SUCCESS";
export const GET_OFFICE_LOCATION_FAIL = "GET_OFFICE_LOCATION_SUCCESS";

export const GET_ALL_JOBTYPE_SUCCESS = "GET_ALL_JOBTYPE_SUCCESS";
export const GET_ALL_JOBTYPE_REQUEST = "GET_ALL_JOBTYPE_REQUEST";
export const GET_ALL_JOBTYPE_FAIL = "GET_ALL_JOBTYPE_FAIL";

export const GET_BAND_BY_ID_SUCCESS = "GET_BAND_BY_ID_SUCCESS";
export const GET_BAND_BY_ID_REQUEST = "GET_BAND_BY_ID_REQUEST";
export const GET_BAND_BY_ID_FAIL = "GET_BAND_BY_ID_FAIL";

export const GET_ALL_HOLIDAYS_SUCCESS = "GET_ALL_HOLIDAYS_SUCCESS";
export const GET_ALL_HOLIDAYS_REQUEST = "GET_ALL_HOLIDAYS_REQUEST";
export const GET_ALL_HOLIDAYS_FAIL = "GET_ALL_HOLIDAYS_FAIL";

export const GET_HOLIDAY_BY_ID_SUCCESS = "GET_HOLIDAY_BY_ID_SUCCESS";
export const GET_HOLIDAY_BY_ID_REQUEST = "GET_HOLIDAY_BY_ID_REQUEST";
export const GET_HOLIDAY_BY_ID_FAIL = "GET_HOLIDAY_BY_ID_FAIL";

export const GET_ALL_DOMINE_SUCCESS = "GET_ALL_DOMINE_SUCCESS";
export const GET_ALL_DOMINE_REQUEST = "GET_ALL_DOMINE_REQUEST";
export const GET_ALL_DOMINE_FAIL = "GET_ALL_DOMINE_FAIL";

export const GET_ALL_COUNTRY_REQUEST = "GET_ALL_COUNTRY_REQUEST";
export const GET_ALL_COUNTRY_SUCCESS = "GET_ALL_COUNTRY_SUCCESS";
export const GET_ALL_COUNTRY_FAIL = "GET_ALL_COUNTRY_FAIL";

export const GET_ALL_STATE_REQUEST = "GET_ALL_COUNTRY_REQUEST";
export const GET_ALL_STATE_SUCCESS = "GET_ALL_STATE_SUCCESS";
export const GET_ALL_STATE_FAIL = "GET_ALL_STATE_FAIL";

export const GET_ALL_CITY_REQUEST = "GET_ALL_CITY_REQUEST";
export const GET_ALL_CITY_SUCCESS = "GET_ALL_STATE_SUCCESS";
export const GET_ALL_CITY_FAIL = "GET_ALL_CITY_FAIL";

export const GET_ALL_CLIENT_DETAILS_REQUEST = "GET_ALL_CLIENT_DETAILS_REQUEST";
export const GET_ALL_CLIENT_DETAILS_SUCCESS = "GET_ALL_CLIENT_DETAILS_SUCCESS";
export const GET_ALL_CLIENT_DETAILS_FAIL = "GET_ALL_CLIENT_DETAILS_FAIL";

export const GET_CLIENT_DETAILS_REQUEST = "GET_CLIENT_DETAILS_REQUEST";
export const GET_CLIENT_DETAILS_SUCCESS = "GET_CLIENT_DETAILS_SUCCESS";
export const GET_CLIENT_DETAILS_FAIL = "GET_CLIENT_DETAILS_FAIL";

export const GET_LOCATION_MASTER_DATA_REQUEST =
  "GET_LOCATION_MASTER_DATA_REQUEST";
export const GET_LOCATION_MASTER_DATA_SUCCESS =
  "GET_LOCATION_MASTER_DATA_SUCCESS";
export const GET_LOCATION_MASTER_DATA_FAIL = "GET_LOCATION_MASTER_DATA_FAIL";

export const GET_ALL_ONSITE_OFFICE_LOCATION_REQUEST =
  "GET_ALL_ONSITE_OFFICE_LOCATION_REQUEST";
export const GET_ALL_ONSITE_OFFICE_LOCATION_SUCCESS =
  "GET_ALL_ONSITE_OFFICE_LOCATION_SUCCESS";
export const GET_ALL_ONSITE_OFFICE_LOCATION_FAIL =
  "GET_ALL_ONSITE_OFFICE_LOCATION_FAIL";

export const GET_ONSITE_OFFICE_LOCATION_REQUEST =
  "GET_ONSITE_OFFICE_LOCATION_REQUEST";
export const GET_ONSITE_OFFICE_LOCATION_SUCCESS =
  "GET_ONSITE_OFFICE_LOCATION_SUCCESS";
export const GET_ONSITE_OFFICE_LOCATION_FAIL =
  "GET_ONSITE_OFFICE_LOCATION_FAIL";

export const ADD_NEW_SKILL_REQUEST = "ADD_NEW_SKILL_REQUEST";
export const ADD_NEW_SKILL_SUCCESS = "ADD_NEW_SKILL_SUCCESS";
export const ADD_NEW_SKILL_FAIL = "ADD_NEW_SKILL_FAIL";

// GET_ALL_DESIGNATION
export const ADD_NEW_DESIGNATION_REQUEST = "ADD_NEW_DESIGNATION_REQUEST";
export const ADD_NEW_DESIGNATION_SUCCESS = "ADD_NEW_DESIGNATION_SUCCESS";
export const ADD_NEW_DESIGNATION_FAIL = "ADD_NEW_DESIGNATION_FAIL";

// GET_ALL_BAND
export const ADD_NEW_BAND_REQUEST = "ADD_NEW_BAND_REQUEST";
export const ADD_NEW_BAND_SUCCESS = "ADD_NEW_BAND_SUCCESS";
export const ADD_NEW_BAND_FAIL = "ADD_NEW_BAND_FAIL";

// GET_ALL_OFFICELOCATION
export const ADD_NEW_OFFICELOCATION_REQUEST = "ADD_NEW_OFFICELOCATION_REQUEST";
export const ADD_NEW_OFFICELOCATION_SUCCESS = "ADD_NEW_OFFICELOCATION_SUCCESS";
export const ADD_NEW_OFFICELOCATION_FAIL = "ADD_NEW_OFFICELOCATION_FAIL";

// GET_ALL_JOBTYPE
export const ADD_NEW_JOBTYPE_REQUEST = "ADD_NEW_JOBTYPE_REQUEST";
export const ADD_NEW_JOBTYPE_SUCCESS = "ADD_NEW_JOBTYPE_SUCCESS";
export const ADD_NEW_JOBTYPE_FAIL = "ADD_NEW_JOBTYPE_FAIL";

// GET_ALL_HOLIDAYS
export const ADD_NEW_HOLIDAY_REQUEST = "ADD_NEW_HOLIDAY_REQUEST";
export const ADD_NEW_HOLIDAY_SUCCESS = "ADD_NEW_HOLIDAY_SUCCESS";
export const ADD_NEW_HOLIDAY_FAIL = "ADD_NEW_HOLIDAY_FAIL";

// GET_ALL_DOMINE
export const ADD_NEW_DOMINE_REQUEST = "ADD_NEW_DOMINE_REQUEST";
export const ADD_NEW_DOMINE_SUCCESS = "ADD_NEW_DOMINE_SUCCESS";
export const ADD_NEW_DOMINE_FAIL = "ADD_NEW_DOMINE_FAIL";

// GET_ALL_CLIENT_DETAILS
export const ADD_NEW_CLIENT_DETAILS_REQUEST = "ADD_NEW_CLIENT_DETAILS_REQUEST";
export const ADD_NEW_CLIENT_DETAILS_SUCCESS = "ADD_NEW_CLIENT_DETAILS_SUCCESS";
export const ADD_NEW_CLIENT_DETAILS_FAIL = "ADD_NEW_CLIENT_DETAILS_FAIL";

// GET_ALL_ONSITE_OFFICE_LOCATION
export const ADD_NEW_ONSITE_OFFICE_LOCATION_REQUEST =
  "ADD_NEW_ONSITE_OFFICE_LOCATION_REQUEST";
export const ADD_NEW_ONSITE_OFFICE_LOCATION_SUCCESS =
  "ADD_NEW_ONSITE_OFFICE_LOCATION_SUCCESS";
export const ADD_NEW_ONSITE_OFFICE_LOCATION_FAIL =
  "ADD_NEW_ONSITE_OFFICE_LOCATION_FAIL";
